### ISSUE TITLE
Possible error in last merge to Master (a31d861a70aebe8507c676a3a3d9aaf74fa24776)

### ISSUE THREAD

**Issue by selrac** [espressif/esp32-at#151]
After pulling new code after this commit (a31d861a70aebe8507c676a3a3d9aaf74fa24776), when I "make" for the first time the project everything is fine. But after a "make clean", when I "make" again this error appears:

> Traceback (most recent call last):
  File "/home/USER/Desktop/ESP32/esp32-at/tools/factory_param_generate.py", line 191, in <module>
    main()
  File "/home/USER/Desktop/ESP32/esp32-at/tools/factory_param_generate.py", line 188, in main
    generate_factory_param_bin(module_file, 'Param_Data', args.bin_name, args.module, args.log_file)
  File "/home/USER/Desktop/ESP32/esp32-at/tools/factory_param_generate.py", line 73, in generate_factory_param_bin
    os.path.remove(log_file)

> 
So I change the "esp32-at/tools/factory_param_generate.py" file, line 73, from:
` os.path.remove(log_file)`
to
` os.remove(log_file)`

Now it seems that after this "fix" this error does not apper anymore.

**Comment by xiewenxiang** [comment]
@selrac 
Thanks for your informations, we will fix it ASAP!
